export const USER_JSON = [
  {
    username: "Dylan1",
    email: "dc@aoe.io",
    password: "testing123",
    firstName: "Dylan",
    lastName: "Comeau",
    userType: "teacher",
  },
  {
    username: "RatchetCat1",
    email: "orangecat@aoe.io",
    password: "testing123",
    firstName: "Ratchet",
    lastName: "Cat",
    userType: "student",
  },
  {
    username: "HuhCat1",
    email: "whitecat@aoe.io",
    password: "testing123",
    firstName: "Huh",
    lastName: "Cat",
    userType: "student",
  },
  {
    username: "SadCat1",
    email: "tabbycat@aoe.io",
    password: "testing123",
    firstName: "Sad",
    lastName: "Cat",
    userType: "student",
  },
  {
    username: "CrunchCat1",
    email: "whitecat2@aoe.io",
    password: "testing123",
    firstName: "Crunch",
    lastName: "Cat",
    userType: "student",
  },
  {
    username: "HappyCat1",
    email: "whitecat3@aoe.io",
    password: "testing123",
    firstName: "Happy",
    lastName: "Cat",
    userType: "student",
  },
  {
    username: "BurritoCat1",
    email: "tabbycat2@aoe.io",
    password: "testing123",
    firstName: "Burrito",
    lastName: "Cat",
    userType: "student",
  },
  {
    username: "realbatman",
    email: "wbruce@aoe.io",
    password: "testing123",
    firstName: "Bruce",
    lastName: "Wayne",
    userType: "teacher",
  },
  {
    username: "realRaven",
    email: "stara@aoe.io",
    password: "testing123",
    firstName: "Tara",
    lastName: "Strong",
    userType: "student",
  },
  {
    username: "realStarfire",
    email: "whyden@aoe.io",
    password: "testing123",
    firstName: "Hynden",
    lastName: "Walch",
    userType: "student",
  },
  {
    username: "realBeastboy",
    email: "cgreg@aoe.io",
    password: "testing123",
    firstName: "Greg",
    lastName: "Cipes",
    userType: "student",
  },
  {
    username: "realRobin",
    email: "mscott@aoe.io",
    password: "testing123",
    firstName: "Scott",
    lastName: "Menville",
    userType: "student",
  },
  {
    username: "realCyborg",
    email: "pkhary@aoe.io",
    password: "testing123",
    firstName: "Khary",
    lastName: "Payton",
    userType: "student",
  },
  {
    username: "teacher1",
    email: "sampleteacher1@aoe.io",
    password: "testing123",
    firstName: "Mr.",
    lastName: "Popovich",
    userType: "teacher",
  },
  {
    username: "popo2",
    email: "samplestud@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr.",
    userType: "student",
  },
  {
    username: "popo3",
    email: "samplestud2@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. II",
    userType: "student",
  },
  {
    username: "popo4",
    email: "samplestud3@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. III",
    userType: "student",
  },
  {
    username: "popo5",
    email: "samplestud4@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. IV",
    userType: "student",
  },
  {
    username: "popo6",
    email: "samplestud5@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. V",
    userType: "student",
  },
  {
    username: "popo7",
    email: "samplestud6@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. VI",
    userType: "student",
  },
  {
    username: "popo8",
    email: "samplestud7@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. VII",
    userType: "student",
  },
  {
    username: "popo9",
    email: "samplestud8@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. VIII",
    userType: "student",
  },
  {
    username: "popo10",
    email: "samplestud9@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. IX",
    userType: "student",
  },
  {
    username: "popo11",
    email: "samplestud10@aoe.io",
    password: "testing123",
    firstName: "Popovich",
    lastName: "Jr. X",
    userType: "student",
  },
  {
    username: "bigbro1",
    email: "bigbro@aoe.io",
    password: "testing123",
    firstName: "Big",
    lastName: "Bro",
    userType: "teacher",
  },
  {
    username: "lilbro1",
    email: "lilbro1@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "lilbro2",
    email: "lilbro2@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "lilbro3",
    email: "lilbro3@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "lilbro4",
    email: "lilbro4@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "lilbro5",
    email: "lilbro5@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "lilbro6",
    email: "lilbro6@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "lilbro7",
    email: "lilbro7@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "lilbro8",
    email: "lilbro8@aoe.io",
    password: "testing123",
    firstName: "Lil",
    lastName: "Bro",
    userType: "student",
  },
  {
    username: "chefcurry",
    email: "stephcurry@aoe.io",
    password: "testing123",
    firstName: "Stephen",
    lastName: "Curry",
    userType: "teacher",
  },
  {
    username: "dametime",
    email: "damelillard@aoe.io",
    password: "testing123",
    firstName: "Damian",
    lastName: "Lillard",
    userType: "student",
  },
  {
    username: "klay3rd",
    email: "kthompson@aoe.io",
    password: "testing123",
    firstName: "Klay",
    lastName: "Thompson",
    userType: "student",
  },
  {
    username: "thaliburton1",
    email: "tburton@aoe.io",
    password: "testing123",
    firstName: "Tyrese",
    lastName: "Haliburton",
    userType: "student",
  },
  {
    username: "thebeard",
    email: "hardenbeard@aoe.io",
    password: "testing123",
    firstName: "James",
    lastName: "Harden",
    userType: "student",
  },
  {
    username: "test1",
    email: "test1@aoe.io",
    password: "testing123",
    firstName: "test",
    lastName: "test",
    userType: "student",
  },
  {
    username: "test2",
    email: "test2@aoe.io",
    password: "testing123",
    firstName: "test",
    lastName: "test",
    userType: "student",
  },
  {
    username: "test3",
    email: "test3@aoe.io",
    password: "testing123",
    firstName: "test",
    lastName: "test",
    userType: "student",
  },
];
